/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_weblinkon_jni_Homomorphism */

#ifndef _Included_com_weblinkon_jni_Homomorphism
#define _Included_com_weblinkon_jni_Homomorphism
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    genkey
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_weblinkon_jni_Homomorphism_genkey
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    encryptCSV
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_weblinkon_jni_Homomorphism_encryptCSV
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    encrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_weblinkon_jni_Homomorphism_encrypt
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    add
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_weblinkon_jni_Homomorphism_add
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    multiply
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_weblinkon_jni_Homomorphism_multiply
  (JNIEnv *, jobject, jstring, jstring, jstring, jstring);

/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    FHEOperationResult
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_weblinkon_jni_Homomorphism_FHEOperationResult
  (JNIEnv *, jobject, jstring, jstring, jstring);

/*
 * Class:     com_weblinkon_jni_Homomorphism
 * Method:    decrypt
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;I)V
 */
JNIEXPORT void JNICALL Java_com_weblinkon_jni_Homomorphism_decrypt
  (JNIEnv *, jobject, jstring, jstring, jstring, jint);

#ifdef __cplusplus
}
#endif
#endif
